### ISSUE TITLE
Any luck if i can add a line horizontally chart programatically

### ISSUE THREAD

**Issue by rockscripts** [rp8/candlejs#1]
Thank you for this module. is it possible for me add a line with this module? how an i add information such date in bottom (X) and prices in rigth side (Y) like second images. 

![screenshot from 2018-06-14 22-50-44](https://user-images.githubusercontent.com/20305057/41442202-90e3854a-7025-11e8-9793-bfcffbe33ce7.png)
![screenshot from 2018-06-14 22-54-41](https://user-images.githubusercontent.com/20305057/41442325-2dc117d8-7026-11e8-8d37-b2d9eb1fe3f6.png)

**Comment by rp8** [comment]
I'm sorry to miss your message. If it's still OK, I have added a new function to add a line in chart. You can find example in test/candle.html.
